services:
  frontend:
    image: remy4657/test-etrade-fe-ci:latest
    networks:
      - etrade-network
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
networks:
  etrade-network:
    external: true
