services:
  frontend:
    image: remy4657/etrade-frontend:latest
    container_name: etrade_frontend
    restart: always
    networks:
      - etrade-network
    env_file:
      - .env.production
    ports:
      - "3000:3000"
networks:
  etrade-network:
    external: true
