services:
  frontend:
    image: remy4657/etrade-frontend:pro
    networks:
      - etrade-network
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.pro
    ports:
      - "3000:3000"
    command: npm run start
networks:
  etrade-network:
    external: true
