services:
  frontend:
    image: etrade-frontend
    networks:
      - etrade-network
    environment:
      - INTERNAL_API_URL=http://backend:8080
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
networks:
  etrade-network:
    external: true
